import React from "react";

const squads = {
  "2022": {
    ODI: {
      "IND vs SL": {
        IND: [
          { name: "Rohit Sharma", runs: 50, balls: 80, wickets: 0 },
          { name: "Virat Kohli", runs: 70, balls: 90, wickets: 0 },
          { name: "KL Rahul", runs: 20, balls: 30, wickets: 0 },
          { name: "Hardik Pandya", runs: 30, balls: 40, wickets: 1 },
          { name: "Jasprit Bumrah", runs: 10, balls: 10, wickets: 2 },
          { name: "Mohammed Shami", runs: 5, balls: 5, wickets: 1 },
          { name: "Ravindra Jadeja", runs: 25, balls: 35, wickets: 1 },
          { name: "Shreyas Iyer", runs: 15, balls: 20, wickets: 0 },
          { name: "Bhuvneshwar Kumar", runs: 15, balls: 20, wickets: 1 },
          { name: "Yuzvendra Chahal", runs: 13, balls: 30, wickets: 2 },
          { name: "Ishan Kishan", runs: 10, balls: 15, wickets: 0 },
        ],
        SL: [
          { name: "Dasun Shanaka", runs: 40, balls: 60, wickets: 1 },
          { name: "Kusal Mendis", runs: 20, balls: 35, wickets: 0 },
          { name: "Dimuth Karunaratne", runs: 10, balls: 15, wickets: 0 },
          { name: "Dhananjaya de Silva", runs: 35, balls: 50, wickets: 0 },
          { name: "Wanindu Hasaranga", runs: 5, balls: 10, wickets: 2 },
          { name: "Shanaka Fernando", runs: 15, balls: 25, wickets: 0 },
          { name: "Niroshan Dickwella", runs: 5, balls: 10, wickets: 0 },
          { name: "Pathum Nissanka", runs: 0, balls: 0, wickets: 1 },
          { name: "Chamika Karunaratne", runs: 0, balls: 0, wickets: 2 },
          { name: "Dushmantha Chameera", runs: 0, balls: 0, wickets: 1 },
          { name: "Maheesh Theekshana", runs: 0, balls: 0, wickets: 1 },
        ],
      },
      "IND vs AUS": {
        IND: [
          { name: "Rohit Sharma", runs: 75, balls: 90, wickets: 0 },
          { name: "Virat Kohli", runs: 80, balls: 95, wickets: 0 },
          { name: "KL Rahul", runs: 50, balls: 70, wickets: 0 },
          { name: "Hardik Pandya", runs: 40, balls: 55, wickets: 1 },
          { name: "Jasprit Bumrah", runs: 20, balls: 30, wickets: 2 },
          { name: "Mohammed Shami", runs: 10, balls: 20, wickets: 0 },
          { name: "Ravindra Jadeja", runs: 15, balls: 25, wickets: 1 },
          { name: "Shreyas Iyer", runs: 5, balls: 10, wickets: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 0 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 2 },
          { name: "Ishan Kishan", runs: 10, balls: 15, wickets: 0 },
        ],
        AUS: [
          { name: "Aaron Finch", runs: 60, balls: 75, wickets: 0 },
          { name: "David Warner", runs: 45, balls: 50, wickets: 0 },
          { name: "Steven Smith", runs: 55, balls: 60, wickets: 0 },
          { name: "Marnus Labuschagne", runs: 30, balls: 40, wickets: 0 },
          { name: "Glenn Maxwell", runs: 20, balls: 25, wickets: 1 },
          { name: "Pat Cummins", runs: 0, balls: 0, wickets: 2 },
          { name: "Mitchell Starc", runs: 0, balls: 0, wickets: 1 },
          { name: "Josh Hazlewood", runs: 0, balls: 0, wickets: 1 },
          { name: "Adam Zampa", runs: 0, balls: 0, wickets: 2 },
          { name: "Marcus Stoinis", runs: 0, balls: 0, wickets: 0 },
          { name: "Alex Carey", runs: 10, balls: 15, wickets: 0 },
        ],
      },
    },
    T20: {
      "IND vs ENG": {
        IND: [
          { name: "Rohit Sharma", runs: 30, balls: 40, wickets: 0 },
          { name: "Virat Kohli", runs: 50, balls: 55, wickets: 0 },
          { name: "KL Rahul", runs: 25, balls: 30, wickets: 0 },
          { name: "Hardik Pandya", runs: 35, balls: 50, wickets: 1 },
          { name: "Jasprit Bumrah", runs: 5, balls: 5, wickets: 2 },
          { name: "Mohammed Shami", runs: 10, balls: 15, wickets: 0 },
          { name: "Ravindra Jadeja", runs: 20, balls: 25, wickets: 1 },
          { name: "Shreyas Iyer", runs: 15, balls: 20, wickets: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 1 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 2 },
          { name: "Ishan Kishan", runs: 10, balls: 15, wickets: 0 },
        ],
        ENG: [
          { name: "Jos Buttler", runs: 45, balls: 50, wickets: 0 },
          { name: "Jason Roy", runs: 35, balls: 40, wickets: 0 },
          { name: "Ben Stokes", runs: 30, balls: 35, wickets: 1 },
          { name: "Eoin Morgan", runs: 20, balls: 25, wickets: 0 },
          { name: "Adil Rashid", runs: 5, balls: 5, wickets: 2 },
          { name: "Jofra Archer", runs: 0, balls: 0, wickets: 1 },
          { name: "Mark Wood", runs: 0, balls: 0, wickets: 1 },
          { name: "Sam Billings", runs: 10, balls: 15, wickets: 0 },
          { name: "Tom Banton", runs: 10, balls: 10, wickets: 0 },
          { name: "Chris Woakes", runs: 0, balls: 0, wickets: 0 },
          { name: "Moeen Ali", runs: 15, balls: 20, wickets: 1 },
        ],
      },
      "IND vs NZ": {
        IND: [
          { name: "Rohit Sharma", runs: 60, balls: 50, wickets: 1, overs: 10 },
          { name: "Virat Kohli", runs: 70, balls: 60, wickets: 0, overs: 0 },
          { name: "KL Rahul", runs: 30, balls: 25, wickets: 0, overs: 0 },
          { name: "Hardik Pandya", runs: 20, balls: 18, wickets: 2, overs: 8 },
          { name: "Jasprit Bumrah", runs: 5, balls: 7, wickets: 1, overs: 10 },
          { name: "Mohammed Shami", runs: 10, balls: 10, wickets: 0, overs: 0 },
          { name: "Ravindra Jadeja", runs: 40, balls: 35, wickets: 0, overs: 0 },
          { name: "Shreyas Iyer", runs: 25, balls: 20, wickets: 0, overs: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Ishan Kishan", runs: 15, balls: 18, wickets: 0, overs: 0 },
        ],
        NZ: [
          { name: "Devon Conway", runs: 55, balls: 45, wickets: 0, overs: 0 },
          { name: "Finn Allen", runs: 35, balls: 30, wickets: 0, overs: 0 },
          { name: "Kane Williamson", runs: 40, balls: 35, wickets: 0, overs: 0 },
          { name: "Ross Taylor", runs: 20, balls: 18, wickets: 0, overs: 0 },
          { name: "Tom Latham", runs: 10, balls: 10, wickets: 1, overs: 10 },
          { name: "James Neesham", runs: 15, balls: 12, wickets: 2, overs: 8 },
          { name: "Mitchell Santner", runs: 5, balls: 6, wickets: 1, overs: 10 },
          { name: "Kyle Jamieson", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Lockie Ferguson", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Trent Boult", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Tim Southee", runs: 0, balls: 0, wickets: 1, overs: 10 },
        ],
      },
    },
  },
  "2023": {
    ODI: {
      "IND vs PAK": {
        IND: [
          { name: "Rohit Sharma", runs: 60, balls: 80, wickets: 0 },
          { name: "Virat Kohli", runs: 100, balls: 120, wickets: 0 },
          { name: "KL Rahul", runs: 40, balls: 50, wickets: 1 },
          { name: "Hardik Pandya", runs: 20, balls: 25, wickets: 1 },
          { name: "Jasprit Bumrah", runs: 10, balls: 10, wickets: 2 },
          { name: "Mohammed Shami", runs: 5, balls: 5, wickets: 1 },
          { name: "Ravindra Jadeja", runs: 35, balls: 45, wickets: 1 },
          { name: "Shreyas Iyer", runs: 20, balls: 30, wickets: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 1 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 2 },
          { name: "Ishan Kishan", runs: 15, balls: 20, wickets: 0 },
        ],
        PAK: [
          { name: "Babar Azam", runs: 50, balls: 60, wickets: 0 },
          { name: "Mohammad Rizwan", runs: 40, balls: 50, wickets: 0 },
          { name: "Fakhar Zaman", runs: 20, balls: 30, wickets: 0 },
          { name: "Shadab Khan", runs: 25, balls: 35, wickets: 1 },
          { name: "Shaheen Afridi", runs: 10, balls: 10, wickets: 2 },
          { name: "Mohammad Nawaz", runs: 15, balls: 20, wickets: 1 },
          { name: "Harish Sohail", runs: 5, balls: 10, wickets: 0 },
          { name: "Asif Ali", runs: 5, balls: 10, wickets: 0 },
          { name: "Wahab Riaz", runs: 0, balls: 0, wickets: 0 },
          { name: "Shan Masood", runs: 10, balls: 15, wickets: 0 },
          { name: "Haris Rauf", runs: 0, balls: 0, wickets: 1 },
        ],
      },
      "IND vs AFG": {
        IND: [
          { name: "Rohit Sharma", runs: 80, balls: 90, wickets: 1, overs: 10 },
          { name: "Virat Kohli", runs: 60, balls: 70, wickets: 0, overs: 0 },
          { name: "KL Rahul", runs: 40, balls: 50, wickets: 0, overs: 0 },
          { name: "Hardik Pandya", runs: 25, balls: 30, wickets: 2, overs: 8 },
          { name: "Jasprit Bumrah", runs: 10, balls: 10, wickets: 1, overs: 10 },
          { name: "Mohammed Shami", runs: 5, balls: 8, wickets: 0, overs: 0 },
          { name: "Ravindra Jadeja", runs: 20, balls: 15, wickets: 0, overs: 0 },
          { name: "Shreyas Iyer", runs: 35, balls: 40, wickets: 0, overs: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Ishan Kishan", runs: 15, balls: 20, wickets: 0, overs: 0 },
        ],
        AFG: [
          { name: "Rahmanullah Gurbaz", runs: 40, balls: 50, wickets: 0, overs: 0 },
          { name: "Hashmatullah Shahidi", runs: 70, balls: 80, wickets: 0, overs: 0 },
          { name: "Rashid Khan", runs: 10, balls: 12, wickets: 2, overs: 10 },
          { name: "Mohammad Nabi", runs: 30, balls: 25, wickets: 1, overs: 10 },
          { name: "Fazalhaq Farooqi", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Mujeeb Ur Rahman", runs: 0, balls: 0, wickets: 1, overs: 10 },
          { name: "Gulbadin Naib", runs: 15, balls: 20, wickets: 0, overs: 0 },
          { name: "Asghar Afghan", runs: 25, balls: 30, wickets: 0, overs: 0 },
          { name: "Najibullah Zadran", runs: 20, balls: 18, wickets: 0, overs: 0 },
          { name: "Karim Janat", runs: 10, balls: 12, wickets: 0, overs: 0 },
          { name: "Zahir Khan", runs: 0, balls: 0, wickets: 0, overs: 0 },
        ],
      },
    },
    T20: {
      "IND vs SA": {
        IND: [
          { name: "Rohit Sharma", runs: 40, balls: 30, wickets: 1, overs: 4 },
          { name: "Virat Kohli", runs: 60, balls: 40, wickets: 0, overs: 0 },
          { name: "KL Rahul", runs: 50, balls: 45, wickets: 0, overs: 0 },
          { name: "Hardik Pandya", runs: 35, balls: 25, wickets: 2, overs: 4 },
          { name: "Jasprit Bumrah", runs: 5, balls: 5, wickets: 1, overs: 4 },
          { name: "Mohammed Shami", runs: 10, balls: 10, wickets: 0, overs: 0 },
          { name: "Ravindra Jadeja", runs: 20, balls: 15, wickets: 0, overs: 0 },
          { name: "Shreyas Iyer", runs: 25, balls: 20, wickets: 0, overs: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Ishan Kishan", runs: 15, balls: 12, wickets: 0, overs: 0 },
        ],
        SA: [
          { name: "Quinton de Kock", runs: 70, balls: 50, wickets: 0, overs: 0 },
          { name: "Aiden Markram", runs: 30, balls: 25, wickets: 0, overs: 0 },
          { name: "Temba Bavuma", runs: 20, balls: 15, wickets: 0, overs: 0 },
          { name: "David Miller", runs: 40, balls: 30, wickets: 0, overs: 0 },
          { name: "Kagiso Rabada", runs: 5, balls: 5, wickets: 2, overs: 4 },
          { name: "Lungi Ngidi", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Tabraiz Shamsi", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Dwaine Pretorius", runs: 10, balls: 10, wickets: 1, overs: 4 },
          { name: "Anrich Nortje", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Rassie van der Dussen", runs: 25, balls: 20, wickets: 0, overs: 0 },
          { name: "Keshav Maharaj", runs: 0, balls: 0, wickets: 0, overs: 0 },
        ],
      },
      "IND vs WI": {
        IND: [
          { name: "Rohit Sharma", runs: 50, balls: 40, wickets: 0, overs: 0 },
          { name: "Virat Kohli", runs: 35, balls: 30, wickets: 0, overs: 0 },
          { name: "KL Rahul", runs: 60, balls: 45, wickets: 1, overs: 4 },
          { name: "Hardik Pandya", runs: 25, balls: 20, wickets: 1, overs: 4 },
          { name: "Jasprit Bumrah", runs: 10, balls: 8, wickets: 2, overs: 4 },
          { name: "Mohammed Shami", runs: 15, balls: 10, wickets: 0, overs: 0 },
          { name: "Ravindra Jadeja", runs: 20, balls: 15, wickets: 0, overs: 0 },
          { name: "Shreyas Iyer", runs: 30, balls: 25, wickets: 0, overs: 0 },
          { name: "Bhuvneshwar Kumar", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Yuzvendra Chahal", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Ishan Kishan", runs: 5, balls: 6, wickets: 0, overs: 0 },
        ],
        WI: [
          { name: "Kieron Pollard", runs: 45, balls: 35, wickets: 0, overs: 0 },
          { name: "Nicholas Pooran", runs: 50, balls: 40, wickets: 0, overs: 0 },
          { name: "Shai Hope", runs: 30, balls: 25, wickets: 0, overs: 0 },
          { name: "Chris Gayle", runs: 20, balls: 18, wickets: 0, overs: 0 },
          { name: "Jason Holder", runs: 10, balls: 12, wickets: 1, overs: 4 },
          { name: "Obed McCoy", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Andre Russell", runs: 0, balls: 0, wickets: 2, overs: 4 },
          { name: "Shimron Hetmyer", runs: 15, balls: 10, wickets: 0, overs: 0 },
          { name: "Hayden Walsh", runs: 0, balls: 0, wickets: 1, overs: 4 },
          { name: "Kyle Mayers", runs: 5, balls: 6, wickets: 0, overs: 0 },
          { name: "Evin Lewis", runs: 0, balls: 0, wickets: 0, overs: 0 },
        ],
      },
    }
  },
}

export default squads;
